/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

package manipulation.joint;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * @brief 单个关节的控制命令
 *
 */
public final class single_joint_command_t implements lcm.lcm.LCMEncodable
{
    /**
     * 目标位置
     */
    public float pos;

    /**
     * 目标速度  
     */
    public float vel;

 
    public single_joint_command_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xc63bc8eb2c8de205L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(manipulation.joint.single_joint_command_t.class))
            return 0L;
 
        classes.add(manipulation.joint.single_joint_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeFloat(this.pos); 
 
        outs.writeFloat(this.vel); 
 
    }
 
    public single_joint_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public single_joint_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static manipulation.joint.single_joint_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        manipulation.joint.single_joint_command_t o = new manipulation.joint.single_joint_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.pos = ins.readFloat();
 
        this.vel = ins.readFloat();
 
    }
 
    public manipulation.joint.single_joint_command_t copy()
    {
        manipulation.joint.single_joint_command_t outobj = new manipulation.joint.single_joint_command_t();
        outobj.pos = this.pos;
 
        outobj.vel = this.vel;
 
        return outobj;
    }
 
}

