/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package manipulation.joint;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class single_joint_state_t implements lcm.lcm.LCMEncodable
{
    public short status_word;
    public float posH;
    public float posL;
    public float vel;
    public float toq;
    public float current;
    public short err_code;
 
    public single_joint_state_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x11ee4d4379ef2430L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(manipulation.joint.single_joint_state_t.class))
            return 0L;
 
        classes.add(manipulation.joint.single_joint_state_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeShort(this.status_word); 
 
        outs.writeFloat(this.posH); 
 
        outs.writeFloat(this.posL); 
 
        outs.writeFloat(this.vel); 
 
        outs.writeFloat(this.toq); 
 
        outs.writeFloat(this.current); 
 
        outs.writeShort(this.err_code); 
 
    }
 
    public single_joint_state_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public single_joint_state_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static manipulation.joint.single_joint_state_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        manipulation.joint.single_joint_state_t o = new manipulation.joint.single_joint_state_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.status_word = ins.readShort();
 
        this.posH = ins.readFloat();
 
        this.posL = ins.readFloat();
 
        this.vel = ins.readFloat();
 
        this.toq = ins.readFloat();
 
        this.current = ins.readFloat();
 
        this.err_code = ins.readShort();
 
    }
 
    public manipulation.joint.single_joint_state_t copy()
    {
        manipulation.joint.single_joint_state_t outobj = new manipulation.joint.single_joint_state_t();
        outobj.status_word = this.status_word;
 
        outobj.posH = this.posH;
 
        outobj.posL = this.posL;
 
        outobj.vel = this.vel;
 
        outobj.toq = this.toq;
 
        outobj.current = this.current;
 
        outobj.err_code = this.err_code;
 
        return outobj;
    }
 
}

