/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

package hal.gripper;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * @brief 单个夹爪关节的状态
 *
 */
public final class single_gripper_joint_state_t implements lcm.lcm.LCMEncodable
{
    /**
     * 状态字
     */
    public short status_word;

    /**
     * 实际位置
     * LCM Type: float[1]
     */
    public float pos[];

    /**
     * 实际力矩
     * LCM Type: float[1]
     */
    public float toq[];

    /**
     * 实际电流
     * LCM Type: float[1]
     */
    public float cur[];

    /**
     * 错误码
     */
    public short error_code;

 
    public single_gripper_joint_state_t()
    {
        pos = new float[1];
        toq = new float[1];
        cur = new float[1];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8aaa9aba8875c486L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(hal.gripper.single_gripper_joint_state_t.class))
            return 0L;
 
        classes.add(hal.gripper.single_gripper_joint_state_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeShort(this.status_word); 
 
        for (int a = 0; a < 1; a++) {
            outs.writeFloat(this.pos[a]); 
        }
 
        for (int a = 0; a < 1; a++) {
            outs.writeFloat(this.toq[a]); 
        }
 
        for (int a = 0; a < 1; a++) {
            outs.writeFloat(this.cur[a]); 
        }
 
        outs.writeShort(this.error_code); 
 
    }
 
    public single_gripper_joint_state_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public single_gripper_joint_state_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static hal.gripper.single_gripper_joint_state_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        hal.gripper.single_gripper_joint_state_t o = new hal.gripper.single_gripper_joint_state_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.status_word = ins.readShort();
 
        this.pos = new float[(int) 1];
        for (int a = 0; a < 1; a++) {
            this.pos[a] = ins.readFloat();
        }
 
        this.toq = new float[(int) 1];
        for (int a = 0; a < 1; a++) {
            this.toq[a] = ins.readFloat();
        }
 
        this.cur = new float[(int) 1];
        for (int a = 0; a < 1; a++) {
            this.cur[a] = ins.readFloat();
        }
 
        this.error_code = ins.readShort();
 
    }
 
    public hal.gripper.single_gripper_joint_state_t copy()
    {
        hal.gripper.single_gripper_joint_state_t outobj = new hal.gripper.single_gripper_joint_state_t();
        outobj.status_word = this.status_word;
 
        outobj.pos = new float[(int) 1];
        System.arraycopy(this.pos, 0, outobj.pos, 0, 1); 
        outobj.toq = new float[(int) 1];
        System.arraycopy(this.toq, 0, outobj.toq, 0, 1); 
        outobj.cur = new float[(int) 1];
        System.arraycopy(this.cur, 0, outobj.cur, 0, 1); 
        outobj.error_code = this.error_code;
 
        return outobj;
    }
 
}

