/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package hal.gripper;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class single_gripper_joint_command_t implements lcm.lcm.LCMEncodable
{
    public short operation_mode;
    public float pos[];
 
    public single_gripper_joint_command_t()
    {
        pos = new float[1];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x06a856bb0d5ee7f6L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(hal.gripper.single_gripper_joint_command_t.class))
            return 0L;
 
        classes.add(hal.gripper.single_gripper_joint_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeShort(this.operation_mode); 
 
        for (int a = 0; a < 1; a++) {
            outs.writeFloat(this.pos[a]); 
        }
 
    }
 
    public single_gripper_joint_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public single_gripper_joint_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static hal.gripper.single_gripper_joint_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        hal.gripper.single_gripper_joint_command_t o = new hal.gripper.single_gripper_joint_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.operation_mode = ins.readShort();
 
        this.pos = new float[(int) 1];
        for (int a = 0; a < 1; a++) {
            this.pos[a] = ins.readFloat();
        }
 
    }
 
    public hal.gripper.single_gripper_joint_command_t copy()
    {
        hal.gripper.single_gripper_joint_command_t outobj = new hal.gripper.single_gripper_joint_command_t();
        outobj.operation_mode = this.operation_mode;
 
        outobj.pos = new float[(int) 1];
        System.arraycopy(this.pos, 0, outobj.pos, 0, 1); 
        return outobj;
    }
 
}

