/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

package hal.suction;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * @brief 电动吸盘控制命令 (钧舵 EVS08, RS-485 Modbus RTU)
 * 控制模式 operation_mode:
 *   0 = 空闲 (无操作)
 *   1 = 初始化 (使能 rACT + 写高级模式参数)
 *   2 = 吸取 (双通道联动; vacuum_pct/detect_vacuum_pct/grip_timeout_100ms 可覆盖配置)
 *   3 = 释放 (双通道联动, 破真空)
 *   4 = 停止 (真空发生器停, 阀门保持工件位置)
 *   5 = 使能 (rACT=1)
 *   6 = 停止并清故障 (rACT=0)
 * EVS08 为双通道控制器 (四吸嘴 2+2 分接 CH1/CH2), 消息结构不变, 枚举扩展单通道控制:
 *   11 = 仅 CH1 吸取   12 = 仅 CH2 吸取
 *   13 = 仅 CH1 释放   14 = 仅 CH2 释放
 * 真空度换算: 寄存器值 = 100 - 真空度%, 最大 70%
 * 协议详见《JODELL 钧舵 EVS08 系列电动吸盘通用详细说明书 V1.1》第 6/7 章
 *
 */
public final class suction_command_t implements lcm.lcm.LCMEncodable
{
    /**
     * 时间戳（纳秒）
     */
    public long timestamp;

    /**
     * 控制模式 (见上)
     */
    public short operation_mode;

    /**
     * 目标真空度 % (0~70, operation_mode=2 时有效; <=0 用配置默认值)
     */
    public float vacuum_pct;

    /**
     * 检测工件最小真空度 % (operation_mode=2 时有效; -1 用配置默认值, 0=无最低检测)
     */
    public float detect_vacuum_pct;

    /**
     * 抓取超时 (100ms/单位, operation_mode=2 时有效; -1 用配置默认值, 0=不检测超时)
     */
    public float grip_timeout_100ms;

 
    public suction_command_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x5d1b95ac09391ae3L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(hal.suction.suction_command_t.class))
            return 0L;
 
        classes.add(hal.suction.suction_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeShort(this.operation_mode); 
 
        outs.writeFloat(this.vacuum_pct); 
 
        outs.writeFloat(this.detect_vacuum_pct); 
 
        outs.writeFloat(this.grip_timeout_100ms); 
 
    }
 
    public suction_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public suction_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static hal.suction.suction_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        hal.suction.suction_command_t o = new hal.suction.suction_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.operation_mode = ins.readShort();
 
        this.vacuum_pct = ins.readFloat();
 
        this.detect_vacuum_pct = ins.readFloat();
 
        this.grip_timeout_100ms = ins.readFloat();
 
    }
 
    public hal.suction.suction_command_t copy()
    {
        hal.suction.suction_command_t outobj = new hal.suction.suction_command_t();
        outobj.timestamp = this.timestamp;
 
        outobj.operation_mode = this.operation_mode;
 
        outobj.vacuum_pct = this.vacuum_pct;
 
        outobj.detect_vacuum_pct = this.detect_vacuum_pct;
 
        outobj.grip_timeout_100ms = this.grip_timeout_100ms;
 
        return outobj;
    }
 
}

