/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package hal.suction;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class suction_command_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public short operation_mode;
    public float vacuum_pct;
    public float detect_vacuum_pct;
    public float grip_timeout_100ms;
 
    public suction_command_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x5d1b95ac09391ae3L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(hal.suction.suction_command_t.class))
            return 0L;
 
        classes.add(hal.suction.suction_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeShort(this.operation_mode); 
 
        outs.writeFloat(this.vacuum_pct); 
 
        outs.writeFloat(this.detect_vacuum_pct); 
 
        outs.writeFloat(this.grip_timeout_100ms); 
 
    }
 
    public suction_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public suction_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static hal.suction.suction_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        hal.suction.suction_command_t o = new hal.suction.suction_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.operation_mode = ins.readShort();
 
        this.vacuum_pct = ins.readFloat();
 
        this.detect_vacuum_pct = ins.readFloat();
 
        this.grip_timeout_100ms = ins.readFloat();
 
    }
 
    public hal.suction.suction_command_t copy()
    {
        hal.suction.suction_command_t outobj = new hal.suction.suction_command_t();
        outobj.timestamp = this.timestamp;
 
        outobj.operation_mode = this.operation_mode;
 
        outobj.vacuum_pct = this.vacuum_pct;
 
        outobj.detect_vacuum_pct = this.detect_vacuum_pct;
 
        outobj.grip_timeout_100ms = this.grip_timeout_100ms;
 
        return outobj;
    }
 
}

