/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

package hal.suction;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * @brief 电动吸盘状态
 * 状态字 status_word (每通道一份):
 *   bit0 = 使能 (gACT)
 *   bit1 = 调节真空度中 (gGTO)
 *   bit2 = 工件已吸住 (仅 gOBJ=01/10; gOBJ=11 丢失/脱落不算, gGTO=0 时 gOBJ 无效)
 *   bit3 = 存在故障 (fault_code != 0)
 * comm_ok = 1 表示本次读取成功; 0 表示 485 通信失败/设备离线,
 * 此时其余字段为最后有效值 (冻结), 上层应据此判定设备状态不可信。
 * EVS08 为双通道控制器 (四吸嘴 2+2 分接 CH1/CH2), channels 数组固定 2 个:
 *   channels[0] = CH1 状态/压差, channels[1] = CH2 状态/压差
 * 温度/母线电压/故障为设备级字段, 不随通道复制。
 * 故障位 fault_code (EVS08 说明书 §6.3.2, 低 9 位):
 *   0x001 CH1 吸取超时(红灯慢闪)  0x002 CH2 吸取超时
 *   0x004 通讯丢失(蓝灯慢闪)      0x008 CH1 掉落(蓝灯快闪)  0x010 CH2 掉落
 *   0x020 电压故障(红灯快闪)      0x040 电压告警(红蓝交替)  0x080 过温≥85℃(红灯常亮)
 *   0x100 产品自身故障
 *
 */
public final class suction_channel_state_t implements lcm.lcm.LCMEncodable
{
    /**
     * 状态字 (位定义见上)
     */
    public short status_word;

    /**
     * 实际压差 KPa (负=真空, 正=正压; Pdiff = gPO - 100)
     */
    public float pressure_diff_kpa;

 
    public suction_channel_state_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x6e5d98bfe2915e06L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(hal.suction.suction_channel_state_t.class))
            return 0L;
 
        classes.add(hal.suction.suction_channel_state_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeShort(this.status_word); 
 
        outs.writeFloat(this.pressure_diff_kpa); 
 
    }
 
    public suction_channel_state_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public suction_channel_state_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static hal.suction.suction_channel_state_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        hal.suction.suction_channel_state_t o = new hal.suction.suction_channel_state_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.status_word = ins.readShort();
 
        this.pressure_diff_kpa = ins.readFloat();
 
    }
 
    public hal.suction.suction_channel_state_t copy()
    {
        hal.suction.suction_channel_state_t outobj = new hal.suction.suction_channel_state_t();
        outobj.status_word = this.status_word;
 
        outobj.pressure_diff_kpa = this.pressure_diff_kpa;
 
        return outobj;
    }
 
}

