/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package manipulation.robot;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class robot_info_t implements lcm.lcm.LCMEncodable
{
    public long timestamp_ns;
    public String vendor;
    public String robot_id;
    public String robot_type;
    public String controller_version;
    public int joint_num;
    public short power_state;
    public short operate_mode;
    public short operation_state;
    public byte connected;
 
    public robot_info_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x4d99831eeda04136L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(manipulation.robot.robot_info_t.class))
            return 0L;
 
        classes.add(manipulation.robot.robot_info_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.timestamp_ns); 
 
        __strbuf = new char[this.vendor.length()]; this.vendor.getChars(0, this.vendor.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        __strbuf = new char[this.robot_id.length()]; this.robot_id.getChars(0, this.robot_id.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        __strbuf = new char[this.robot_type.length()]; this.robot_type.getChars(0, this.robot_type.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        __strbuf = new char[this.controller_version.length()]; this.controller_version.getChars(0, this.controller_version.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.joint_num); 
 
        outs.writeShort(this.power_state); 
 
        outs.writeShort(this.operate_mode); 
 
        outs.writeShort(this.operation_state); 
 
        outs.writeByte(this.connected); 
 
    }
 
    public robot_info_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public robot_info_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static manipulation.robot.robot_info_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        manipulation.robot.robot_info_t o = new manipulation.robot.robot_info_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.timestamp_ns = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.vendor = new String(__strbuf);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.robot_id = new String(__strbuf);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.robot_type = new String(__strbuf);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.controller_version = new String(__strbuf);
 
        this.joint_num = ins.readInt();
 
        this.power_state = ins.readShort();
 
        this.operate_mode = ins.readShort();
 
        this.operation_state = ins.readShort();
 
        this.connected = ins.readByte();
 
    }
 
    public manipulation.robot.robot_info_t copy()
    {
        manipulation.robot.robot_info_t outobj = new manipulation.robot.robot_info_t();
        outobj.timestamp_ns = this.timestamp_ns;
 
        outobj.vendor = this.vendor;
 
        outobj.robot_id = this.robot_id;
 
        outobj.robot_type = this.robot_type;
 
        outobj.controller_version = this.controller_version;
 
        outobj.joint_num = this.joint_num;
 
        outobj.power_state = this.power_state;
 
        outobj.operate_mode = this.operate_mode;
 
        outobj.operation_state = this.operation_state;
 
        outobj.connected = this.connected;
 
        return outobj;
    }
 
}

