/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

package manipulation.arm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * @brief 单个手臂关节控制命令
 *
 */
public final class joint_command_t implements lcm.lcm.LCMEncodable
{
    /**
     * 时间戳（纳秒）
     */
    public long timestamp;

    /**
     * 多个关节的状态集合，关节顺序：手臂7关节             
     * LCM Type: manipulation.joint.single_joint_command_t[7]
     */
    public manipulation.joint.single_joint_command_t joints[];

 
    public joint_command_t()
    {
        joints = new manipulation.joint.single_joint_command_t[7];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x50bf32ee95033226L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(manipulation.arm.joint_command_t.class))
            return 0L;
 
        classes.add(manipulation.arm.joint_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + manipulation.joint.single_joint_command_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        for (int a = 0; a < 7; a++) {
            this.joints[a]._encodeRecursive(outs); 
        }
 
    }
 
    public joint_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public joint_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static manipulation.arm.joint_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        manipulation.arm.joint_command_t o = new manipulation.arm.joint_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.joints = new manipulation.joint.single_joint_command_t[(int) 7];
        for (int a = 0; a < 7; a++) {
            this.joints[a] = manipulation.joint.single_joint_command_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public manipulation.arm.joint_command_t copy()
    {
        manipulation.arm.joint_command_t outobj = new manipulation.arm.joint_command_t();
        outobj.timestamp = this.timestamp;
 
        outobj.joints = new manipulation.joint.single_joint_command_t[(int) 7];
        for (int a = 0; a < 7; a++) {
            outobj.joints[a] = this.joints[a].copy();
        }
 
        return outobj;
    }
 
}

