/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

package hal.canfd;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * @brief 整个状态信息
 *
 */
public final class canfd_state_t implements lcm.lcm.LCMEncodable
{
    /**
     * 时间戳（纳秒）
     */
    public long timestamp;

    /**
     * 关节数量        
     */
    public int num_joints;

    /**
     * 所有关节状态          
     * LCM Type: hal.canfd.single_canfd_joint_state_t[num_joints]
     */
    public hal.canfd.single_canfd_joint_state_t joints[];

 
    public canfd_state_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xec273c130ce0cc76L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(hal.canfd.canfd_state_t.class))
            return 0L;
 
        classes.add(hal.canfd.canfd_state_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + hal.canfd.single_canfd_joint_state_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeInt(this.num_joints); 
 
        for (int a = 0; a < this.num_joints; a++) {
            this.joints[a]._encodeRecursive(outs); 
        }
 
    }
 
    public canfd_state_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public canfd_state_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static hal.canfd.canfd_state_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        hal.canfd.canfd_state_t o = new hal.canfd.canfd_state_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.num_joints = ins.readInt();
 
        this.joints = new hal.canfd.single_canfd_joint_state_t[(int) num_joints];
        for (int a = 0; a < this.num_joints; a++) {
            this.joints[a] = hal.canfd.single_canfd_joint_state_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public hal.canfd.canfd_state_t copy()
    {
        hal.canfd.canfd_state_t outobj = new hal.canfd.canfd_state_t();
        outobj.timestamp = this.timestamp;
 
        outobj.num_joints = this.num_joints;
 
        outobj.joints = new hal.canfd.single_canfd_joint_state_t[(int) num_joints];
        for (int a = 0; a < this.num_joints; a++) {
            outobj.joints[a] = this.joints[a].copy();
        }
 
        return outobj;
    }
 
}

