/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

package hal.canfd;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * @brief 单个关节的状态
 *
 */
public final class single_canfd_joint_state_t implements lcm.lcm.LCMEncodable
{
    /**
     * 当前关节状态
     */
    public short status_word;

    /**
     * 可选状态参数
     */
    public short state_args;

    /**
     * 当前关节位置
     */
    public float pos;

    /**
     * 当前速度
     */
    public float vel;

    /**
     * 当前力矩
     */
    public float toq;

    /**
     * 当前电流
     */
    public float current;

    /**
     * 可配置上传参数
     */
    public float para_data;

    /**
     * 错误码
     */
    public short err_code;

    /**
     * 预留字段, 自身canid号, 0x00表示离线
     */
    public short reserved;

 
    public single_canfd_joint_state_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x462d82a4f8905730L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(hal.canfd.single_canfd_joint_state_t.class))
            return 0L;
 
        classes.add(hal.canfd.single_canfd_joint_state_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeShort(this.status_word); 
 
        outs.writeShort(this.state_args); 
 
        outs.writeFloat(this.pos); 
 
        outs.writeFloat(this.vel); 
 
        outs.writeFloat(this.toq); 
 
        outs.writeFloat(this.current); 
 
        outs.writeFloat(this.para_data); 
 
        outs.writeShort(this.err_code); 
 
        outs.writeShort(this.reserved); 
 
    }
 
    public single_canfd_joint_state_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public single_canfd_joint_state_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static hal.canfd.single_canfd_joint_state_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        hal.canfd.single_canfd_joint_state_t o = new hal.canfd.single_canfd_joint_state_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.status_word = ins.readShort();
 
        this.state_args = ins.readShort();
 
        this.pos = ins.readFloat();
 
        this.vel = ins.readFloat();
 
        this.toq = ins.readFloat();
 
        this.current = ins.readFloat();
 
        this.para_data = ins.readFloat();
 
        this.err_code = ins.readShort();
 
        this.reserved = ins.readShort();
 
    }
 
    public hal.canfd.single_canfd_joint_state_t copy()
    {
        hal.canfd.single_canfd_joint_state_t outobj = new hal.canfd.single_canfd_joint_state_t();
        outobj.status_word = this.status_word;
 
        outobj.state_args = this.state_args;
 
        outobj.pos = this.pos;
 
        outobj.vel = this.vel;
 
        outobj.toq = this.toq;
 
        outobj.current = this.current;
 
        outobj.para_data = this.para_data;
 
        outobj.err_code = this.err_code;
 
        outobj.reserved = this.reserved;
 
        return outobj;
    }
 
}

