/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

package hal.canfd;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * @brief 单个关节的控制命令
 *
 */
public final class single_canfd_joint_command_t implements lcm.lcm.LCMEncodable
{
    /**
     * CAN节点
     */
    public short can_node;

    /**
     * 控制字，工作模式
     */
    public short operation_mode;

    /**
     * 可选指令参数
     */
    public short cmd_args;

    /**
     * 目标位置
     */
    public float pos;

    /**
     * 目标速度
     */
    public float vel;

    /**
     * 目标力矩
     */
    public float toq;

    /**
     * 位置增益
     */
    public float kp;

    /**
     * 速度增益
     */
    public float kd;

    /**
     * 预留字段
     */
    public short reserved;

 
    public single_canfd_joint_command_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x60e8df152e420ed6L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(hal.canfd.single_canfd_joint_command_t.class))
            return 0L;
 
        classes.add(hal.canfd.single_canfd_joint_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeShort(this.can_node); 
 
        outs.writeShort(this.operation_mode); 
 
        outs.writeShort(this.cmd_args); 
 
        outs.writeFloat(this.pos); 
 
        outs.writeFloat(this.vel); 
 
        outs.writeFloat(this.toq); 
 
        outs.writeFloat(this.kp); 
 
        outs.writeFloat(this.kd); 
 
        outs.writeShort(this.reserved); 
 
    }
 
    public single_canfd_joint_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public single_canfd_joint_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static hal.canfd.single_canfd_joint_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        hal.canfd.single_canfd_joint_command_t o = new hal.canfd.single_canfd_joint_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.can_node = ins.readShort();
 
        this.operation_mode = ins.readShort();
 
        this.cmd_args = ins.readShort();
 
        this.pos = ins.readFloat();
 
        this.vel = ins.readFloat();
 
        this.toq = ins.readFloat();
 
        this.kp = ins.readFloat();
 
        this.kd = ins.readFloat();
 
        this.reserved = ins.readShort();
 
    }
 
    public hal.canfd.single_canfd_joint_command_t copy()
    {
        hal.canfd.single_canfd_joint_command_t outobj = new hal.canfd.single_canfd_joint_command_t();
        outobj.can_node = this.can_node;
 
        outobj.operation_mode = this.operation_mode;
 
        outobj.cmd_args = this.cmd_args;
 
        outobj.pos = this.pos;
 
        outobj.vel = this.vel;
 
        outobj.toq = this.toq;
 
        outobj.kp = this.kp;
 
        outobj.kd = this.kd;
 
        outobj.reserved = this.reserved;
 
        return outobj;
    }
 
}

