"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class suction_channel_state_t(object):
    __slots__ = ["status_word", "pressure_diff_kpa"]

    __typenames__ = ["int16_t", "float"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.status_word = 0
        self.pressure_diff_kpa = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(suction_channel_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hf", self.status_word, self.pressure_diff_kpa))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != suction_channel_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return suction_channel_state_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = suction_channel_state_t()
        self.status_word, self.pressure_diff_kpa = struct.unpack(">hf", buf.read(6))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if suction_channel_state_t in parents: return 0
        tmphash = (0x6e5d98bfe2915e06) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if suction_channel_state_t._packed_fingerprint is None:
            suction_channel_state_t._packed_fingerprint = struct.pack(">Q", suction_channel_state_t._get_hash_recursive([]))
        return suction_channel_state_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", suction_channel_state_t._get_packed_fingerprint())[0]

