"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import manipulation.suction.suction_channel_state_t

class suction_state_t(object):
    __slots__ = ["timestamp", "channels", "temperature_c", "bus_voltage_v", "fault_code", "comm_ok"]

    __typenames__ = ["int64_t", "manipulation.suction.suction_channel_state_t", "float", "float", "int16_t", "int8_t"]

    __dimensions__ = [None, [2], None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        self.channels = [ manipulation.suction.suction_channel_state_t() for dim0 in range(2) ]
        self.temperature_c = 0.0
        self.bus_voltage_v = 0.0
        self.fault_code = 0
        self.comm_ok = 0

    def encode(self):
        buf = BytesIO()
        buf.write(suction_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        for i0 in range(2):
            assert self.channels[i0]._get_packed_fingerprint() == manipulation.suction.suction_channel_state_t._get_packed_fingerprint()
            self.channels[i0]._encode_one(buf)
        buf.write(struct.pack(">ffhb", self.temperature_c, self.bus_voltage_v, self.fault_code, self.comm_ok))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != suction_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return suction_state_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = suction_state_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.channels = []
        for i0 in range(2):
            self.channels.append(manipulation.suction.suction_channel_state_t._decode_one(buf))
        self.temperature_c, self.bus_voltage_v, self.fault_code, self.comm_ok = struct.unpack(">ffhb", buf.read(11))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if suction_state_t in parents: return 0
        newparents = parents + [suction_state_t]
        tmphash = (0xf42a502bcb363e0e+ manipulation.suction.suction_channel_state_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if suction_state_t._packed_fingerprint is None:
            suction_state_t._packed_fingerprint = struct.pack(">Q", suction_state_t._get_hash_recursive([]))
        return suction_state_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", suction_state_t._get_packed_fingerprint())[0]

