"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class suction_command_t(object):
    __slots__ = ["timestamp", "operation_mode", "vacuum_pct", "detect_vacuum_pct", "grip_timeout_100ms"]

    __typenames__ = ["int64_t", "int16_t", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        self.operation_mode = 0
        self.vacuum_pct = 0.0
        self.detect_vacuum_pct = 0.0
        self.grip_timeout_100ms = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(suction_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qhfff", self.timestamp, self.operation_mode, self.vacuum_pct, self.detect_vacuum_pct, self.grip_timeout_100ms))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != suction_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return suction_command_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = suction_command_t()
        self.timestamp, self.operation_mode, self.vacuum_pct, self.detect_vacuum_pct, self.grip_timeout_100ms = struct.unpack(">qhfff", buf.read(22))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if suction_command_t in parents: return 0
        tmphash = (0x5d1b95ac09391ae3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if suction_command_t._packed_fingerprint is None:
            suction_command_t._packed_fingerprint = struct.pack(">Q", suction_command_t._get_hash_recursive([]))
        return suction_command_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", suction_command_t._get_packed_fingerprint())[0]

