/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

package manipulation.suction;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class suction_state_t implements lcm.lcm.LCMEncodable
{
    /**
     * 时间戳（纳秒）
     */
    public long timestamp;

    /**
     * 通道状态 (固定 2 个: [0]=CH1, [1]=CH2; 单通道设备 channels[1] 保持 0)
     * LCM Type: manipulation.suction.suction_channel_state_t[2]
     */
    public manipulation.suction.suction_channel_state_t channels[];

    /**
     * 板上温度 ℃
     */
    public float temperature_c;

    /**
     * 母线电压 V
     */
    public float bus_voltage_v;

    /**
     * 故障寄存器低 9 位 (见上)
     */
    public short fault_code;

    /**
     * 通信在线位 (1=正常, 0=读取失败/设备离线, 其余字段冻结)
     */
    public byte comm_ok;

 
    public suction_state_t()
    {
        channels = new manipulation.suction.suction_channel_state_t[2];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xf42a502bcb363e0eL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(manipulation.suction.suction_state_t.class))
            return 0L;
 
        classes.add(manipulation.suction.suction_state_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + manipulation.suction.suction_channel_state_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        for (int a = 0; a < 2; a++) {
            this.channels[a]._encodeRecursive(outs); 
        }
 
        outs.writeFloat(this.temperature_c); 
 
        outs.writeFloat(this.bus_voltage_v); 
 
        outs.writeShort(this.fault_code); 
 
        outs.writeByte(this.comm_ok); 
 
    }
 
    public suction_state_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public suction_state_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static manipulation.suction.suction_state_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        manipulation.suction.suction_state_t o = new manipulation.suction.suction_state_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.channels = new manipulation.suction.suction_channel_state_t[(int) 2];
        for (int a = 0; a < 2; a++) {
            this.channels[a] = manipulation.suction.suction_channel_state_t._decodeRecursiveFactory(ins);
        }
 
        this.temperature_c = ins.readFloat();
 
        this.bus_voltage_v = ins.readFloat();
 
        this.fault_code = ins.readShort();
 
        this.comm_ok = ins.readByte();
 
    }
 
    public manipulation.suction.suction_state_t copy()
    {
        manipulation.suction.suction_state_t outobj = new manipulation.suction.suction_state_t();
        outobj.timestamp = this.timestamp;
 
        outobj.channels = new manipulation.suction.suction_channel_state_t[(int) 2];
        for (int a = 0; a < 2; a++) {
            outobj.channels[a] = this.channels[a].copy();
        }
 
        outobj.temperature_c = this.temperature_c;
 
        outobj.bus_voltage_v = this.bus_voltage_v;
 
        outobj.fault_code = this.fault_code;
 
        outobj.comm_ok = this.comm_ok;
 
        return outobj;
    }
 
}

