/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package manipulation.suction;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class suction_channel_state_t implements lcm.lcm.LCMEncodable
{
    public short status_word;
    public float pressure_diff_kpa;
 
    public suction_channel_state_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x6e5d98bfe2915e06L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(manipulation.suction.suction_channel_state_t.class))
            return 0L;
 
        classes.add(manipulation.suction.suction_channel_state_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeShort(this.status_word); 
 
        outs.writeFloat(this.pressure_diff_kpa); 
 
    }
 
    public suction_channel_state_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public suction_channel_state_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static manipulation.suction.suction_channel_state_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        manipulation.suction.suction_channel_state_t o = new manipulation.suction.suction_channel_state_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.status_word = ins.readShort();
 
        this.pressure_diff_kpa = ins.readFloat();
 
    }
 
    public manipulation.suction.suction_channel_state_t copy()
    {
        manipulation.suction.suction_channel_state_t outobj = new manipulation.suction.suction_channel_state_t();
        outobj.status_word = this.status_word;
 
        outobj.pressure_diff_kpa = this.pressure_diff_kpa;
 
        return outobj;
    }
 
}

